# Generated by Django 3.0.1 on 2019-12-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sub_to_not',
            field=models.BooleanField(default=False, verbose_name='sub to not'),
        ),
    ]
