# Generated by Django 3.0.1 on 2019-12-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_sub_to_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sub_to_not',
            field=models.BooleanField(default=False, verbose_name='Получать уведомления?'),
        ),
    ]
